### ISSUE TITLE
Unable to Compile Structure Mapping Files into Structure Maps  

### ISSUE THREAD

**Issue by KMCGit** [hapifhir/org.hl7.fhir.core#1163]
I am unable to compile Mapping files into Structure Maps with newer versions of the Validator, including newest version attempted (5.6.105) 

FHIR Validation tool Version 5.6.105 (Git# 0b8e2c39841b). Built 2023-03-09T13:08:33.436Z (6 hours old)
  Java:   11.0.12 from /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home on x86_64 (64bit). 16384MB available
  Paths:  Current = /Users/Kenneth.Crawford/Documents/dev/extract-newmaps/sdc-extract, Package Cache = /Users/Kenneth.Crawford/.fhir/packages
  Params: -ig map/SDOHCC-PersonalCharacteristicsMap-Ken.map -compile https://fhirserver-connectathon.azurewebsites.net/StructureMap/SDOHCC-StructureMapPersonalCharacteristics -version 4.0 -output map/SDOHCC-Personal-Characteristics-Map-Ken.json
  Jurisdiction: United States of America
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1.Can't find BackboneElement profile http://hl7.org/fhir/StructureDefinition/document-section-library but trying to go on
Can't find BackboneElement profile http://hl7.org/fhir/StructureDefinition/document-section-library but trying to go on
Can't find BackboneElement profile http://hl7.org/fhir/StructureDefinition/document-section-library but trying to go on
: - 4576 resources (00:06.231)
  Load hl7.terminology#5.1.0 - 4180 resources (00:02.015)
  Load R5 Extensions - 144 resources (00:02.441)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:00.654)
  Load map/SDOHCC-PersonalCharacteristicsMap.map* load file: map/SDOHCC-PersonalCharacteristicsMap.fml - ignored due to error:  (null - NPE)
java.lang.NullPointerException
        at org.hl7.fhir.r4.utils.StructureMapUtilities.parseSource(StructureMapUtilities.java:1125)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.parseRule(StructureMapUtilities.java:1000)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.parseGroup(StructureMapUtilities.java:951)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.parse(StructureMapUtilities.java:746)
        at org.hl7.fhir.validation.IgLoader.loadResourceByVersion(IgLoader.java:795)
        at org.hl7.fhir.validation.IgLoader.loadFileWithErrorChecking(IgLoader.java:760)
        at org.hl7.fhir.validation.IgLoader.loadIg(IgLoader.java:139)
        at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:407)
        at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:375)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:283)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:138)
 - 0 resources (00:00.023)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.0.12, hl7.terminology#5.1.0]
  Get set...  go (00:00.014)
 ...Failure Unable to locate map https://fhirserver.azurewebsites.net/StructureMap/SDOHCC-StructureMapPersonalCharacteristics
java.lang.Exception: Unable to locate map https://fhirserver.azurewebsites.net/StructureMap/SDOHCC-StructureMapPersonalCharacteristics
        at org.hl7.fhir.validation.cli.services.ValidationService.compile(ValidationService.java:342)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:290)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:138)
Done. Times: Loading: 00:11.957. Max Memory = 16Gb

**Comment by grahamegrieve** [comment]
I don't see how there could possibly be an NPE on that line unless java itself is bung. Please provide an example map

**Comment by KMCGit** [comment]
If I use the FHIR Validation tool Version 5.6.81 I can compile. I will share an example map below, it is a modified version of the HL7 map for Hunger Vital Signs. 

[SDOHCC-Hunger-Vital-Sign-Dev.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/10943843/SDOHCC-Hunger-Vital-Sign-Dev.txt)

Thanks for responding and have a great day.

**Comment by grahamegrieve** [comment]
the problem is in line #799 of IgLoader, where StructureMapUtilities is constructed without a context, because there can't be one, but the parser requires a context if it's going to parse the source. I don't know how this could ever have worked - will have to prowl through the version history to get insight, but whatever, I don't know how to make this work

**Comment by igorboss** [comment]
It seems I created a similar task https://github.com/hapifhir/org.hl7.fhir.core/issues/1182

**Comment by oliveregger** [comment]
I think this is also related to #1182

**Comment by KMCGit** [comment]
Any update as to this? Have pulled the latest as of 3/31 
seeing below:

Load map/SDOHCC-Hunger-Vital-Sign-Dev.map* load file: map/SDOHCC-Hunger-Vital-Sign-Dev.fml - ignored due to error:  (null - NPE)
java.lang.NullPointerException
        at org.hl7.fhir.r4.utils.StructureMapUtilities.parseSource(StructureMapUtilities.java:1125)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.parseRule(StructureMapUtilities.java:1000)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.parseGroup(StructureMapUtilities.java:951)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.parse(StructureMapUtilities.java:746)
        at org.hl7.fhir.validation.IgLoader.loadResourceByVersion(IgLoader.java:799)
        at org.hl7.fhir.validation.IgLoader.loadFileWithErrorChecking(IgLoader.java:764)
        at org.hl7.fhir.validation.IgLoader.loadIg(IgLoader.java:140)
        at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:407)
        at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:375)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:303)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:144)
 - 0 resources (00:00.020)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.0.12, hl7.terminology#5.1.0]
  Get set...  go (00:00.023)
 ...Failure: Unable to locate map https://fhirserver-dev.azurewebsites.net/StructureMap/SDOHCC-StructureMapHungerVitalSign
java.lang.Exception: Unable to locate map https://fhirserver-dev.azurewebsites.net/StructureMap/SDOHCC-StructureMapHungerVitalSign
        at org.hl7.fhir.validation.cli.services.ValidationService.compile(ValidationService.java:342)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:310)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:144)

**Comment by KMCGit** [comment]
This was addressed in other issues and is operating as expected once again. Thanks for addressing the issue.
