### ISSUE TITLE
Issue with the compilation of the FML map

### ISSUE THREAD

**Issue by igorboss** [hapifhir/org.hl7.fhir.core#1182]
I have an issue with the compilation of the FML map. 
I downloaded https://github.com/ahdis/fhir-mapping-tutorial and tried to compile a map in the "maptutuorial/step2" (zip of step2 attached).
I renamed step2.xml in the map folder (you can also delete it) and tried different possibilities to compile step2.map (to get compiled map - step2.xml).
I tried:
java -jar ../../validator_cli.jar -ig logical -ig map/step2.map -compile "http://hl7.org/fhir/StructureMap/tutorial-step2" -version 4.0.1 -output xxx. txt
and:
java -jar ../../validator_cli.jar -ig map/step2.map -compile "http://hl7.org/fhir/StructureMap/tutorial-step2" -version 4.0.1 -output xxx.txt
and:
java -jar ../../validator_cli.jar -ig logical -ig map/step2.map -compile "tutorial-step2" -version 4.0.1 -output xxx.txt
The result is always the same:
Load map/step2.map* load file: map/step2.txt - ignored due to error: Cannot invoke "org.hl7.fhir.r4.context.IWorkerContext.allStructures()" because "worker" is null
0 resources (00:00.012)
Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.0.12, hl7.terminology#5.1.0]
Get set... go (00:00.005)
...Failure: Unable to locate map http://hl7.org/fhir/StructureMap/tutorial-step2
java.lang.Exception: Unable to locate map http://hl7.org/fhir/StructureMap/tutorial-step2
at org.hl7.fhir.validation.cli.services.ValidationService.compile(ValidationService.java:323)
at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:290)
at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:138)
I think any working example will help us to understand what is wrong with local compilation.

I can compile map file using ahdis.ch/matchbox server (it is means all files are valid), but I wish to do this using shell. Is it possible to provide working example of fix validator?
[step2.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/11040210/step2.zip)

**Comment by oliveregger** [comment]
i will have a look

**Comment by igorboss** [comment]
No, I don't need R4 anymore. But compilation failed with both - previous version of validator_cli and with latest. The compilation with latest version returns 
`(base) igor@Igors-MBP step2 % java -jar validator_cli.jar -ig logical -ig map/step2.map -compile http://hl7.org/fhir/StructureMap/tutorial-step2 -version 5.0.0 -output map/step2.xml 
FHIR Validation tool Version 5.6.115 (Git# e68a6171eed7). Built 2023-03-25T12:25:46.780Z (56 hours old)
  Java:   17.0.5 from /opt/homebrew/Cellar/openjdk@17/17.0.5/libexec/openjdk.jdk/Contents/Home on aarch64 (64bit). 8192MB available
  Paths:  Current = /Users/igor/source/taltech/mapping-tutorial/maptutorial/step2, Package Cache = /Users/igor/.fhir/packages
  Params: -ig logical -ig map/step2.map -compile http://hl7.org/fhir/StructureMap/tutorial-step2 -version 5.0.0 -output map/step2.xml
  Jurisdiction: Estonia
Loading
  Load FHIR vcurrent from hl7.fhir.r5.core#5.0.0.:Error fetching http://packages.fhir.org/hl7.fhir.uv.extensions: Invalid HTTP response 404 from http://packages.fhir.org/hl7.fhir.uv.extensions (Not Found) (content in /var/folders/mt/l989rf1j61j6wf5448tkly0c0000gn/T/fhir-http-2.log)
2023-03-27 23:26:25.122 [main] INFO  o.h.f.u.n.FilesystemPackageCacheManager [FilesystemPackageCacheManager.java:261] Failed to determine latest version of package hl7.fhir.uv.extensions from server: http://packages.fhir.org
  Load hl7.terminology.r5#5.0.0 - 4174 resources (00:06.047)
  Load hl7.fhir.uv.extensions#1.0.0 - 1328 resources (00:00.012)
 - 8454 resources (00:00.000)
  Load hl7.terminology#5.1.0 - 4180 resources (00:00.709)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:01.684)
  Load logical - 2 resources (00:00.041)
  Load map/step2.map* load file: map/step2.fml - ignored due to error: Error @2, 4: Found draft expecting "[status]"
org.hl7.fhir.r5.utils.FHIRLexer$FHIRLexerException: Error @2, 4: Found draft expecting "[status]"
	at org.hl7.fhir.r5.utils.FHIRLexer.error(FHIRLexer.java:169)
	at org.hl7.fhir.r5.utils.FHIRLexer.error(FHIRLexer.java:165)
	at org.hl7.fhir.r5.utils.FHIRLexer.readConstant(FHIRLexer.java:428)
	at org.hl7.fhir.r5.utils.structuremap.StructureMapUtilities.parse(StructureMapUtilities.java:663)
	at org.hl7.fhir.validation.IgLoader.loadResourceByVersion(IgLoader.java:840)
	at org.hl7.fhir.validation.IgLoader.loadFileWithErrorChecking(IgLoader.java:764)
	at org.hl7.fhir.validation.IgLoader.loadIg(IgLoader.java:140)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:407)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:375)
	at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:303)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:144)
 - 0 resources (00:01.001)
  Package Summary: [hl7.fhir.r5.core#5.0.0, hl7.fhir.xver-extensions#0.0.12, hl7.terminology.r5#5.0.0, hl7.fhir.uv.extensions#1.0.0, hl7.terminology#5.1.0]
  Get set...  go (00:00.006)
 ...Failure: Unable to locate map http://hl7.org/fhir/StructureMap/tutorial-step2
java.lang.Exception: Unable to locate map http://hl7.org/fhir/StructureMap/tutorial-step2
	at org.hl7.fhir.validation.cli.services.ValidationService.compile(ValidationService.java:342)
	at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:310)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:144)
`

**Comment by oliveregger** [comment]
yes, but this is now a different error: : Error @2, 4: Found draft expecting "[status]". Could it be, that you did not yet pull the newest map from the master branch?

**Comment by igorboss** [comment]
Thank you for your advice. Now it works!
