### ISSUE TITLE
Fhir Validator Version 5.x can't load R5 Extensions

### ISSUE THREAD

**Issue by krebbl** [hapifhir/org.hl7.fhir.core#1269]
When running the Validator 5.x I get the following error since last week:

```
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1.: - 4576 resources (00:07.170)
  Load hl7.terminology#5.1.0 - 4180 resources (00:01.787)
  Load R5 Extensions ...

Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to fetch: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchFromUrlSpecific(FilesystemPackageCacheManager.java:567)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadFromCIBuild(FilesystemPackageCacheManager.java:587)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadPackage(FilesystemPackageCacheManager.java:547)
	at org.hl7.fhir.r5.conformance.R5ExtensionsLoader.load(R5ExtensionsLoader.java:83)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:397)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:375)
	at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:303)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:144)
Caused by: java.io.IOException: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)
	at org.hl7.fhir.utilities.SimpleHTTPClient$HTTPResult.checkThrowException(SimpleHTTPClient.java:75)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchFromUrlSpecific(FilesystemPackageCacheManager.java:561)
	... 7 more
```

Would be nice if someone could make this package available again.

Thanks

**Comment by grahamegrieve** [comment]
you need to upgrade to a more recent version of the validator - this was fixed last week

**Comment by krebbl** [comment]
thanks, unfortunately this leads me to this issue: https://github.com/hapifhir/org.hl7.fhir.core/issues/1270
