### ISSUE TITLE
Validator CLI: NullPointerException when snapshotting certain core profiles

### ISSUE THREAD

**Issue by DarthGizka** [hapifhir/org.hl7.fhir.core#1287]
Steps to reproduce *(the caret - which denotes line continuation in the Windows shell - is only there for readability and not relevant to the problem at hand)*:

```
java -jar validator_cli-6.0.11.jar ^
   -version 5.0 -tx n/a ^
   StructureDefinition-cdshooksg*.json ^
   -snapshot -outputSuffix snapshot.json
```

Output:

```
FHIR Validation tool Version 6.0.11 (Git# 44db9547439f). Built 2023-06-02T14:25:08.722Z (167 mins old)
  Java:   17.0.7 from C:\Program Files\Java\jdk-17 on amd64 (64bit). 8120MB available

WARNING: Default file encoding is windows-1252 which may cause unexpected results.
         To fix this issue, run this program with the parameter '-Dfile.encoding=UTF-8'
         Future releases may not be able to run at all with encoding windows-1252

  Paths:  Current = x:\package, Package Cache = C:\Users\KnightOwl\.fhir\packages
  Params: -version 5.0 -tx n/a StructureDefinition-cdshooksguidanceresponse.json -snapshot -outputSuffix snapshot.json
  Locale: United States/US
  Jurisdiction: United States of America
Loading
  Load FHIR v5.0 from hl7.fhir.r5.core#5.0.0  Load hl7.terminology.r5#5.0.0 - 4174 resources (00:05.763)
  Load hl7.fhir.uv.extensions#1.0.0 - 1328 resources (00:00.028)
 - 8454 resources (00:00.000)
  Load hl7.terminology#5.1.0 - 4180 resources (00:01.047)
  Terminology server null - Version n/a: No Terminology Server (00:00.000)
  Package Summary: [hl7.fhir.r5.core#5.0.0, hl7.fhir.xver-extensions#0.0.12, hl7.terminology.r5#5.0.0, hl7.fhir.uv.extensions#1.0.0, hl7.terminology#5.1.0]
  Get set...  go (00:01.177)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this.messages" is null
        at org.hl7.fhir.r5.conformance.profile.ProfileUtilities.generateSnapshot(ProfileUtilities.java:781)
        at org.hl7.fhir.validation.ValidationEngine.snapshot(ValidationEngine.java:747)
        at org.hl7.fhir.validation.cli.services.ValidationService.generateSnapshot(ValidationService.java:291)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:336)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:153)
```

Change the last letter before the asterisk in the filename mask from `g` to `r` in order to see a working example. Change it to `s` to see another explosion.

Non-exhaustive testing sees the problem in 6.0.8 and 6.0.11 but not in 5.6.117, 6.01, 6.0.6 and 6.0.7.

**Comment by grahamegrieve** [comment]
Unable to find/resolve/read StructureDefinition-cdshooksg*.json - what's your actual command line / what's in the folder?

**Comment by DarthGizka** [comment]
```
~/.fhir/packages/hl7.fhir.r5.core#5.0.0/package/
```

Sorry for the sloppy/incomplete report.

**Comment by grahamegrieve** [comment]
works for me
