### ISSUE TITLE
Validation crash when CodeSystem.content=not-present and CodeSystem.count is populated

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [hapifhir/org.hl7.fhir.core#1404]
Hi,

I have several CodeSystem resources where `CodeSystem.content` is set to _not-present_ (without any `CodeSystem.concept`'s defined), and `CodeSystem.count` is set to 0 to support this. The latest version of the Validator throws an exception on this combination.

Now, on close reading of the definition of `CodeSystem.count`, it seems to be an error on our side to populate it with a value of 0, but the exception seems to occur with other values for `CodeSystem.count` as well.

Here's the output for [an example CodeSystem resource:](https://github.com/Nictiz/Nictiz-R4-zib2020/blob/88189448d30e9131526894f56058778fee06d824/resources/zib/terminology/codesystem-DSM_5-dsm5.xml) (link, because I can't attach an XML file to the issue):
```
> java -jar validator_cli.jar -version 4.0.1 codesystem-DSM_5-dsm5.xml
FHIR Validation tool Version 6.1.0 (Git# e90863a271b0). Built 2023-08-22T17:27:30.977Z (21 hours old)
  Java:   17.0.7 from C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot on amd64 (64bit). 3938MB available

WARNING: Default file encoding is windows-1252 which may cause unexpected results.
         To fix this issue, run this program with the parameter '-Dfile.encoding=UTF-8'
         Future releases may not be able to run at all with encoding windows-1252

  Paths:  Current = C:\Users\Edelman\Nictiz-R4-Zib2020\resources\zib\terminology, Package Cache = C:\Users\Edelman\.fhir\packages
  Params: -version 4.0.1 codesystem-DSM_5-dsm5.xml
  Locale: United States/US
  Jurisdiction: United States of America
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4576 resources (00:08.862)
  Load hl7.fhir.uv.extensions.r4#1.0.0 - 1328 resources (00:01.205)
  Load hl7.terminology#5.2.0 - 4195 resources (00:01.797)
  Load hl7.terminology.r5#5.0.0 - 4174 resources (00:02.012)
  Load hl7.fhir.uv.extensions#1.0.0 - 1328 resources (00:00.060)
  Terminology server http://tx.fhir.org - Version 3.0.0 (00:01.285)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.0.12, hl7.fhir.uv.extensions.r4#1.0.0, hl7.terminology#5.2.0, hl7.terminology.r5#5.0.0, hl7.fhir.uv.extensions#1.0.0]
  Get set...  go (00:05.689)
Validating
  Validate codesystem-DSM_5-dsm5.xml
Validate CodeSystem against http://hl7.org/fhir/StructureDefinition/CodeSystem|4.0.1..........20..........40..........60..........80.........Validation Infrastructure fail validating org.hl7.fhir.validation.ValidatorUtils$SourceFile@37baddde: Cannot invoke "org.hl7.fhir.r5.elementmodel.Element.getProperty()" because "element" is null
Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: java.lang.NullPointerException: Cannot invoke "org.hl7.fhir.r5.elementmodel.Element.getProperty()" because "element" is null
        at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:626)
        at org.hl7.fhir.validation.cli.services.ValidationService.validateSources(ValidationService.java:155)
        at org.hl7.fhir.validation.cli.tasks.ValidateTask.executeTask(ValidateTask.java:62)
        at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:337)
        at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:188)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:223)
Caused by: java.lang.NullPointerException: Cannot invoke "org.hl7.fhir.r5.elementmodel.Element.getProperty()" because "element" is null
        at org.hl7.fhir.validation.instance.utils.NodeStack.pushInternal(NodeStack.java:101)
        at org.hl7.fhir.validation.instance.utils.NodeStack.push(NodeStack.java:97)
        at org.hl7.fhir.validation.instance.type.CodeSystemValidator.metaChecks(CodeSystemValidator.java:200)
        at org.hl7.fhir.validation.instance.type.CodeSystemValidator.validateCodeSystem(CodeSystemValidator.java:38)
        at org.hl7.fhir.validation.instance.InstanceValidator.checkSpecials(InstanceValidator.java:5229)
        at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:5197)
        at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:4979)
        at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:6477)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:900)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:752)
        at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:650)
        at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:618)
        ... 5 more
```

**Comment by pieter-edelman-nictiz** [comment]
Issue seems to be resolved with version 6.1.1 of the Validator, thanks!
