### ISSUE TITLE
BundleValidator fails on Composition with several subjects

### ISSUE THREAD

**Issue by adamzkover** [hapifhir/org.hl7.fhir.core#1488]
The same Composition validates standalone. When in a Bundle, the following error is thrown:

```java
Exception in thread "main" java.lang.Error: Attempt to read a single element when there is more than one present (subject)
 	at org.hl7.fhir.r5.elementmodel.Element.getNamedChild(Element.java:709)
 	at org.hl7.fhir.validation.instance.type.BundleValidator.validateDocumentReference(BundleValidator.java:524)
 	at org.hl7.fhir.validation.instance.type.BundleValidator.validateDocument(BundleValidator.java:459)
 	at org.hl7.fhir.validation.instance.type.BundleValidator.validateBundle(BundleValidator.java:72)
 	at org.hl7.fhir.validation.instance.InstanceValidator.checkSpecials(InstanceValidator.java:5454)
 	at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:5428)
 	at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:5186)
 	at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:6901)
 	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:998)
 	at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:835)
 	at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:654)
 	at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:615)
 	at org.hl7.fhir.validation.cli.services.ValidationService.validateSources(ValidationService.java:184)
 	at org.hl7.fhir.validation.cli.tasks.ValidateTask.executeTask(ValidateTask.java:62)
 	at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:380)
 	at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:188)
 	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:223)
```

**Comment by grahamegrieve** [comment]
please attach an example instance

**Comment by DarthGizka** [comment]
Could reproduce on 6.2.3, but only with type `document`, not `collection`.

```xml
<Bundle xmlns="http://hl7.org/fhir">
	<identifier>
		<system value="http://zrbj.eu/NamingSystem/GitHub-Issue"/>
		<value value="1488"/>
	</identifier>
	<type value="document"/>
	<timestamp value="2023-11-11T07:34:12Z"/>
	<entry>
		<fullUrl value="urn:uuid:0f3d28ae-4c27-49eb-987d-c35d536b40f8"/>
		<resource>
			<Composition>
				<status value="final"/>
				<type>
					<coding>
						<system value="http://loinc.org"/>
						<code value="11502-2"/>
					</coding>
				</type>
				<subject>
					<reference value="urn:uuid:0f3d28ae-4c27-49eb-987d-c35d536b40f8"/>
				</subject>
				<subject>
					<reference value="urn:uuid:13ed3afe-3d31-4148-8e95-dd62d140da57"/>
				</subject>
				<date value="2023-11-14"/>
				<author>
					<reference value="urn:uuid:13ed3afe-3d31-4148-8e95-dd62d140da57"/>
				</author>
				<title value="."/>
			</Composition>
		</resource>
	</entry>
	<entry>
		<fullUrl value="urn:uuid:13ed3afe-3d31-4148-8e95-dd62d140da57"/>
		<resource>
			<Organization>
				<name value="Zrbj Laboratories"/>
			</Organization>
		</resource>
	</entry>
</Bundle>
```

**Comment by adamzkover** [comment]
Yes, that is a good example. It produces the same error. Thank you @DarthGizka!

**Comment by grahamegrieve** [comment]
Fixed next release

**Comment by adamzkover** [comment]
The new release works fine, both in the validator and the IG publisher. Thank you!
