### ISSUE TITLE
Error when execute jar file from PHP 

### ISSUE THREAD

**Issue by aanair08** [hapifhir/org.hl7.fhir.core#1495]
I am trying to run validatior_cli.jar from PHP code, and the following error occurred.
```
Exception in thread "main" java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1035)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.initCacheFolder(FilesystemPackageCacheManager.java:178)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.init(FilesystemPackageCacheManager.java:169)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.<init>(FilesystemPackageCacheManager.java:128)
	at org.hl7.fhir.validation.cli.utils.Display.printCliParamsAndInfo(Display.java:23)
	at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:363)
	at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:188)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:223)
```

 I tried to give permission for Apache in the cache directory but the still issue exists.

**Comment by grahamegrieve** [comment]
try again with the latest code, there's now a switch to specify the package cache directory
