### ISSUE TITLE
The package 'hl7.fhir.xver-extensions#0.0.2' is not known to the package server ('http://packages.fhir.org')

### ISSUE THREAD

**Issue by sushmithajram13** [hapifhir/org.hl7.fhir.core#165]
Hi there,
I am getting the following exception when I try the following code in VM. Note : This is happening only in any remote or physical VM and not in my local system.

>java -jar org.hl7.fhir.validator.jar AdvanceBloodPressure.xml  -version 3.0
FHIR Validation tool Version 4.2.13-SNAPSHOT (Git# aef4404405e2). Built 2020-04-02T11:08:19.269+11:00 (46 hours old)
Detected Java version: 1.8.0_211 from C:\Program Files\Java\jre1.8.0_211 on amd64 (64bit). 3641MB available
Arguments: AdvanceBloodPressure.xml -version 3.0
Directories: Current = C:\Users\320008062\Downloads, Package Cache = C:\Users\320008062\.fhir\packages
  .. FHIR Version 3.0, definitions from hl7.fhir.r3.core#3.0.2
  .. connect to tx server @ http://tx.fhir.org
Installing hl7.fhir.r3.core#3.0.2 to the package cache
  Fetching:.......................................................................................
  Installing: ....................................................................................... done.
Installing hl7.fhir.xver-extensions#0.0.2 to the package cache
  Fetching:Exception in thread "main" java.io.IOException: Error reading http://fhir.org/packages/hl7.fhir.xver-extensions/0.0.2/package.tgz: null
        at org.hl7.fhir.utilities.cache.NpmPackage.readStream(NpmPackage.java:292)
        at org.hl7.fhir.utilities.cache.NpmPackage.fromPackage(NpmPackage.java:283)
        at org.hl7.fhir.utilities.cache.PackageCacheManager.addPackageToCache(PackageCacheManager.java:462)
        at org.hl7.fhir.utilities.cache.PackageCacheManager.loadPackage(PackageCacheManager.java:613)
        at org.hl7.fhir.validation.ValidationEngine.loadDefinitions(ValidationEngine.java:347)
        at org.hl7.fhir.validation.ValidationEngine.loadInitialDefinitions(ValidationEngine.java:289)
        at org.hl7.fhir.validation.ValidationEngine.<init>(ValidationEngine.java:322)
        at org.hl7.fhir.validation.Validator.main(Validator.java:586)
Caused by: java.lang.NullPointerException
        at java.io.FilterInputStream.markSupported(Unknown Source)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:160)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:131)
        at org.hl7.fhir.utilities.cache.NpmPackage.readStream(NpmPackage.java:290)
        ... 7 more

Is there something which I am missing?

**Comment by sushmithajram13** [comment]
I found that the package cache was unable to load all the packages in remote VM. So I guess that closed the issue, I zip the old package in my local to VM
