### ISSUE TITLE
R2R3ConversionManager Error

### ISSUE THREAD

**Issue by RokshanJ** [hapifhir/org.hl7.fhir.core#173]
Hi @grahamegrieve 
I am trying to use R2R3ConversionManager for dstu2 to dstu3 conversion. I am getting this error - 

2020-04-14/14:25:26.024/CDT DEBUG (OrgConverterTests.java:71) [t:main] loaded R2 Defs
2020-04-14/14:25:41.421/CDT DEBUG (OrgConverterTests.java:79) [t:main] loaded R3 Defs
2020-04-14/14:25:41.657/CDT DEBUG (OrgConverterTests.java:87) [t:main] loaded R2 to R3 Maps
Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Attempt to make an invalid property 'div' on type Narrative
    at org.hl7.fhir.dstu3.model.Base.makeProperty(Base.java:704)
    at org.hl7.fhir.dstu3.model.Element.makeProperty(Element.java:281)
    at org.hl7.fhir.dstu3.model.Narrative.makeProperty(Narrative.java:349)
    at org.hl7.fhir.dstu3.utils.StructureMapUtilities.processTarget(StructureMapUtilities.java:1649)
    at org.hl7.fhir.dstu3.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1262)
    at org.hl7.fhir.dstu3.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1247)
    at org.hl7.fhir.dstu3.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1282)
    at org.hl7.fhir.dstu3.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1247)
    at org.hl7.fhir.dstu3.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1243)
    at org.hl7.fhir.dstu3.utils.StructureMapUtilities.transform(StructureMapUtilities.java:1221)
    at org.hl7.fhir.convertors.R2R3ConversionManager.convertToR3(R2R3ConversionManager.java:279)
    at org.hl7.fhir.convertors.R2R3ConversionManager.convert(R2R3ConversionManager.java:253)
    at com.accenture.ips.fhirsandbox.sandbox.OrgConverterTests.main(OrgConverterTests.java:119)
 

Any suggestion will be really helpful.
Thanks.

**Comment by ItayGoren** [comment]
can you please add the dstu2 resource and the code you tried to convert with?

**Comment by markiantorno** [comment]
I'm going to close this, as there was no reply. If you need me to look into this issue further, please reopen.
