### ISSUE TITLE
Make sure `messages` is always initialized in ProfileUtilities

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [hapifhir/org.hl7.fhir.core#1740]
I'm trying to use the most recent version of the Validator to generate snapshots for a set of profiles, and I'm running quite consistently into a NullPointerException. For example:
```
$ java -jar validator_cli.jar -version 4.0.1 -ig resources/ -recurse -snapshot -outputSuffix snapshot.json resources/zib/zib-*.xml
--- snip ---
FHIR Validation tool Version 6.3.23 (Git# 2721ebb8c60b). Built 2024-08-28T18:46:12.471Z (12 days old)
  Java:   20.0.2 from C:\Program Files\Eclipse Adoptium\jdk-20.0.2.9-hotspot on amd64 (64bit). 8104MB available
--- snip ---
  Locale: United States/US
  Jurisdiction: United States of America
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4576 resources (00:05.745)
  Load hl7.fhir.uv.extensions.r5#5.1.0 - 1396 resources (00:03.107)
  Load hl7.terminology#6.0.2 - 4243 resources (00:01.097)
  Load hl7.terminology.r5#6.0.2 - 4243 resources (00:00.982)
  Load hl7.fhir.uv.extensions#5.2.0-ballot - 702 resources (00:01.396)
  Terminology server http://tx.fhir.org - Version Connected to Terminology Server at http://tx.fhir.org (00:01.378)
--- snip ---
 - 696 resources (00:02.523)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.1.0, hl7.fhir.uv.extensions.r5#5.1.0, hl7.terminology#6.0.2, hl7.terminology.r5#6.0.2, hl7.fhir.uv.extensions#5.2.0-ballot]
  Terminology Cache at C:\Users\EDELMA~1\AppData\Local\Temp\default-tx-cache
  Get set...  go (00:04.248)
Cached new session. Cache size = 1
 ...generated snapshot [0] successfully (resources/zib/zib-AbilityToDressOneself.xml to resources/zib/zib-AbilityToDressOneself.xml.snapshot.json)
 ...generated snapshot [1] successfully (resources/zib/zib-AbilityToDrink.xml to resources/zib/zib-AbilityToDrink.xml.snapshot.json)
 ...generated snapshot [2] successfully (resources/zib/zib-AbilityToEat.xml to resources/zib/zib-AbilityToEat.xml.snapshot.json)
 ...generated snapshot [3] successfully (resources/zib/zib-AbilityToGroom.xml to resources/zib/zib-AbilityToGroom.xml.snapshot.json)
 ...generated snapshot [4] successfully (resources/zib/zib-AbilityToUseToilet.xml to resources/zib/zib-AbilityToUseToilet.xml.snapshot.json)
 ...generated snapshot [5] successfully (resources/zib/zib-AbilityToWashOneself.xml to resources/zib/zib-AbilityToWashOneself.xml.snapshot.json)
 ...generated snapshot [6] successfully (resources/zib/zib-AddressInformation.xml to resources/zib/zib-AddressInformation.xml.snapshot.json)
 ...generated snapshot [7] successfully (resources/zib/zib-AdvanceDirective.xml to resources/zib/zib-AdvanceDirective.xml.snapshot.json)
 ...generated snapshot [8] successfully (resources/zib/zib-AlcoholUse.xml to resources/zib/zib-AlcoholUse.xml.snapshot.json)
 ...generated snapshot [9] successfully (resources/zib/zib-Alert.xml to resources/zib/zib-Alert.xml.snapshot.json)
 ...generated snapshot [10] successfully (resources/zib/zib-AllergyIntolerance.xml to resources/zib/zib-AllergyIntolerance.xml.snapshot.json)
 ...generated snapshot [11] successfully (resources/zib/zib-AnatomicalLocation.xml to resources/zib/zib-AnatomicalLocation.xml.snapshot.json)
 ...generated snapshot [12] successfully (resources/zib/zib-ApgarScore-1Minute.xml to resources/zib/zib-ApgarScore-1Minute.xml.snapshot.json)
 ...generated snapshot [13] successfully (resources/zib/zib-ApgarScore-5Minute.xml to resources/zib/zib-ApgarScore-5Minute.xml.snapshot.json)
 ...generated snapshot [14] successfully (resources/zib/zib-ApgarScore-10Minute.xml to resources/zib/zib-ApgarScore-10Minute.xml.snapshot.json)
 ...generated snapshot [15] successfully (resources/zib/zib-BarthelADLIndex.xml to resources/zib/zib-BarthelADLIndex.xml.snapshot.json)
 ...generated snapshot [16] successfully (resources/zib/zib-BloodPressure.xml to resources/zib/zib-BloodPressure.xml.snapshot.json)
 ...generated snapshot [17] successfully (resources/zib/zib-BodyHeight.xml to resources/zib/zib-BodyHeight.xml.snapshot.json)
 ...generated snapshot [18] successfully (resources/zib/zib-BodyTemperature.xml to resources/zib/zib-BodyTemperature.xml.snapshot.json)
 ...generated snapshot [19] successfully (resources/zib/zib-BodyWeight.xml to resources/zib/zib-BodyWeight.xml.snapshot.json)
 ...generated snapshot [20] successfully (resources/zib/zib-BowelFunction.xml to resources/zib/zib-BowelFunction.xml.snapshot.json)
 ...generated snapshot [21] successfully (resources/zib/zib-CareTeam.xml to resources/zib/zib-CareTeam.xml.snapshot.json)
 ...generated snapshot [22] successfully (resources/zib/zib-ChecklistPainBehavior.xml to resources/zib/zib-ChecklistPainBehavior.xml.snapshot.json)
 ...generated snapshot [23] successfully (resources/zib/zib-ComfortScale.xml to resources/zib/zib-ComfortScale.xml.snapshot.json)
 ...generated snapshot [24] successfully (resources/zib/zib-ContactInformation-EmailAddresses.xml to resources/zib/zib-ContactInformation-EmailAddresses.xml.snapshot.json)
 ...generated snapshot [25] successfully (resources/zib/zib-ContactInformation-TelephoneNumbers.xml to resources/zib/zib-ContactInformation-TelephoneNumbers.xml.snapshot.json)
 ...generated snapshot [26] successfully (resources/zib/zib-ContactPerson.xml to resources/zib/zib-ContactPerson.xml.snapshot.json)
 ...generated snapshot [27] successfully (resources/zib/zib-DevelopmentChild.xml to resources/zib/zib-DevelopmentChild.xml.snapshot.json)
 ...generated snapshot [28] successfully (resources/zib/zib-DOSScore.xml to resources/zib/zib-DOSScore.xml.snapshot.json)
 ...generated snapshot [29] successfully (resources/zib/zib-DrugUse.xml to resources/zib/zib-DrugUse.xml.snapshot.json)
 ...generated snapshot [30] successfully (resources/zib/zib-Education.xml to resources/zib/zib-Education.xml.snapshot.json)
 ...generated snapshot [31] successfully (resources/zib/zib-Encounter.xml to resources/zib/zib-Encounter.xml.snapshot.json)
 ...generated snapshot [32] successfully (resources/zib/zib-EpisodeOfCare.xml to resources/zib/zib-EpisodeOfCare.xml.snapshot.json)
 ...generated snapshot [33] successfully (resources/zib/zib-FeedingPatternInfant.xml to resources/zib/zib-FeedingPatternInfant.xml.snapshot.json)
 ...generated snapshot [34] successfully (resources/zib/zib-FLACCpainScale.xml to resources/zib/zib-FLACCpainScale.xml.snapshot.json)
 ...generated snapshot [35] successfully (resources/zib/zib-FluidBalance.xml to resources/zib/zib-FluidBalance.xml.snapshot.json)
 ...generated snapshot [36] successfully (resources/zib/zib-FreedomRestrictingIntervention.xml to resources/zib/zib-FreedomRestrictingIntervention.xml.snapshot.json)
 ...generated snapshot [37] successfully (resources/zib/zib-FunctionalOrMentalStatus.xml to resources/zib/zib-FunctionalOrMentalStatus.xml.snapshot.json)
 ...generated snapshot [38] successfully (resources/zib/zib-GlasgowComaScale.xml to resources/zib/zib-GlasgowComaScale.xml.snapshot.json)
 ...generated snapshot [39] successfully (resources/zib/zib-HeadCircumference.xml to resources/zib/zib-HeadCircumference.xml.snapshot.json)
 ...generated snapshot [40] successfully (resources/zib/zib-HealthcareProvider-Organization.xml to resources/zib/zib-HealthcareProvider-Organization.xml.snapshot.json)
 ...generated snapshot [41] successfully (resources/zib/zib-HealthcareProvider.xml to resources/zib/zib-HealthcareProvider.xml.snapshot.json)
 ...generated snapshot [42] successfully (resources/zib/zib-HealthProfessional-Practitioner.xml to resources/zib/zib-HealthProfessional-Practitioner.xml.snapshot.json)
 ...generated snapshot [43] successfully (resources/zib/zib-HealthProfessional-PractitionerRole.xml to resources/zib/zib-HealthProfessional-PractitionerRole.xml.snapshot.json)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this.messages" is null
        at org.hl7.fhir.r5.conformance.profile.ProfileUtilities.updateFromDefinition(ProfileUtilities.java:2738)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processSimplePathWithOneMatchingElementInDifferential(ProfilePathProcessor.java:688)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processSimplePath(ProfilePathProcessor.java:251)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPaths(ProfilePathProcessor.java:181)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processSimplePathWithEmptyDiffMatches(ProfilePathProcessor.java:888)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processSimplePath(ProfilePathProcessor.java:248)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPaths(ProfilePathProcessor.java:181)
        at org.hl7.fhir.r5.conformance.profile.ProfilePathProcessor.processPaths(ProfilePathProcessor.java:155)
        at org.hl7.fhir.r5.conformance.profile.ProfileUtilities.generateSnapshot(ProfileUtilities.java:731)
        at org.hl7.fhir.validation.ValidationEngine.snapshot(ValidationEngine.java:846)
        at org.hl7.fhir.validation.cli.services.ValidationService.generateSnapshot(ValidationService.java:387)
        at org.hl7.fhir.validation.cli.tasks.SnapshotTask.executeTask(SnapshotTask.java:41)
        at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:374)
        at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:171)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:206)
```

I'm not very familiar with the codebase, but it seems like `null` is passed for the `messages` parameter in the constructor of ProfileUtilities because there's an assumption that no messages are emitted. Meanwhile, the ProfileUtilities class does find a reason to emit a message, perhaps because it has evolved in a way that wasn't anticipated at first?

Anyway, wouldn't it be safer to make sure `this.messages` is always initialized? I tried to add a simple check (see #1739 -- not sure if this is the way to go but it demonstrates the idea) and with this check enabled, snapshot generation works without a problem.

**Comment by pieter-edelman-nictiz** [comment]
Solved with #1747
