### ISSUE TITLE
CDA to Fhir Error

### ISSUE THREAD

**Issue by marcheschi** [hapifhir/org.hl7.fhir.core#184]
Hi 
I'm trying to use the validator to convert a CDA to Fhir bundle, but I got this error:
**command**
java -jar org.hl7.fhir.validator.jar d:\EHR_TESTS_ENCOID.xml -transform http://hl7.org/fhir/cda/mapping/ccdaDocumentToFhir -ig hl7.fhir.cda#4.0.1 -ig "C:\Users\paolo\Downloads\ccda-to-fhir-master - 1\ccda-to-fhir-master\mappings" -output c:\temp\bundle.xml -ig hl7.fhir.core
**output**

`FHIR Validation tool Version 4.2.21-SNAPSHOT (Git# 608149e4945e). Built 2020-04-29T14:57:31.75+10:00 (4 hours old)
Detected Java version: 1.8.0_251 from C:\Program Files\Java\jre1.8.0_251 on amd64 (64bit). 1799MB available
Arguments: d:\EHR_TESTS_ENCOID.xml -transform http://hl7.org/fhir/cda/mapping/ccdaDocumentToFhir -ig hl7.fhir.cda#4.0.1 -ig "C:\Users\paolo\Downloads\ccda-to-fhir-master - 1\ccda-to-fhir-master\mappings" -output c:\temp\bundle.xml -ig hl7.fhir.core
Directories: Current = C:\Users\paolo\Downloads\ccda-to-fhir-master - 1, Package Cache = C:\Users\paolo\.fhir\packages
  .. FHIR Version current, definitions from hl7.fhir.r5.core#current
  .. connect to tx server @ http://tx.fhir.org
    (vcurrent)
+  .. load IG from hl7.fhir.cda#4.0.1
Installing hl7.fhir.cda#4.0.1 to the package cache
  Fetching:Exception in thread "main" java.io.IOException: Error reading http://hl7.org/fhir/cda/4.0.1/package.tgz: null
        at org.hl7.fhir.utilities.cache.NpmPackage.readStream(NpmPackage.java:304)
        at org.hl7.fhir.utilities.cache.NpmPackage.fromPackage(NpmPackage.java:295)
        at org.hl7.fhir.utilities.cache.PackageCacheManager.addPackageToCache(PackageCacheManager.java:462)
        at org.hl7.fhir.utilities.cache.PackageCacheManager.loadPackage(PackageCacheManager.java:613)
        at org.hl7.fhir.validation.ValidationEngine.resolvePackage(ValidationEngine.java:632)
        at org.hl7.fhir.validation.ValidationEngine.fetchByPackage(ValidationEngine.java:626)
        at org.hl7.fhir.validation.ValidationEngine.loadIgSource(ValidationEngine.java:460)
        at org.hl7.fhir.validation.ValidationEngine.loadIg(ValidationEngine.java:724)
        at org.hl7.fhir.validation.cli.services.ValidationService.getValidator(ValidationService.java:174)
        at org.hl7.fhir.validation.Validator.main(Validator.java:165)
Caused by: java.lang.NullPointerException
        at java.io.FilterInputStream.markSupported(Unknown Source)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:160)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:131)
        at org.hl7.fhir.utilities.cache.NpmPackage.readStream(NpmPackage.java:302)
        ... 9 more`

Can you point me in the right direction on how to use the tool to make the conversion?
Thank you
Paolo

**Comment by marcheschi** [comment]
Also the latest version 4.2.22 looks for the http://hl7.org/fhir/cda/4.0.1/package.tgz package that does not exist.
Paolo

**Comment by marcheschi** [comment]
So this is unfixable ?
Paolo

**Comment by grahamegrieve** [comment]
no, we were just cleaning out old issues, see if anyone cared. Is it still a problem?

**Comment by harishanchu** [comment]
Yes it is still a problem.
