### ISSUE TITLE
ClassCastException in NpmPackage.fhirVersion when fhirVersion is null

### ISSUE THREAD

**Issue by mzgtrifork** [hapifhir/org.hl7.fhir.core#188]
When loading and parsing the npm package "ehelse.fhir.no.grunndata" version "2.2.2" from packages.fhir.org and subsequently reading its fhir version, the following exception is thrown from NpmPackage:

```javascript
2020-05-01 20:01:10.916 [main] ERROR c.u.f.jpa.packages.IgInstallerTestR4 [LoggingRule.java:75] Exception thrown in test case [installIgForR4FromSimplifier(ca.uhn.fhir.jpa.packages.IgInstallerTestR4)]: java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonNull and com.google.gson.JsonArray are in unnamed module of loader 'app')
java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonNull and com.google.gson.JsonArray are in unnamed module of loader 'app')
	at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:195)
	at org.hl7.fhir.utilities.cache.NpmPackage.fhirVersion(NpmPackage.java:529)
	at ca.uhn.fhir.jpa.packages.IgInstaller.install(IgInstaller.java:151)
	at ca.uhn.fhir.jpa.packages.IgInstaller.install(IgInstaller.java:132)
	at ca.uhn.fhir.jpa.packages.IgInstallerTestR4.installIgForR4FromSimplifier(IgInstallerTestR4.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at ca.uhn.fhir.test.utilities.LoggingRule$1.evaluate(LoggingRule.java:72)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
2020-05-01 20:01:10.917 [main] INFO  c.u.f.jpa.packages.IgInstallerTestR4 [LoggingRule.java:78] Finished test case [installIgForR4FromSimplifier(ca.uhn.fhir.jpa.packages.IgInstallerTestR4)] (success=false)
```

Inspecting the package.json I see that 

```javascript
{
  "name": "ehelse.fhir.no.grunndata",
  "version": "2.2.2",
  "description": "Grunndata profiles\r\nHL7 FHIR R4\r\nhl7.fhir.no.basis 2.0.11",
  "devDependencies": null,
  "canonicals": null,
  "author": "thomiz",
  "fhirVersions": null,
  "dependencies": {
    "hl7.fhir.no.basis": "2.0.11",
    "simplifier.core.r4": "4.0.1"
  }
}
```

The NpmPackage should probably handle the case where "fhirVersions" is null.

**Comment by grahamegrieve** [comment]
well, that's a non-compliance in the package, which you should report to simplifier, but ok, I updated the code to still work in that case

**Comment by wardweistra** [comment]
We've prevented this being empty in newly created packages from Simplifier.net just now. Thanks for reporting.
