### ISSUE TITLE
R3 to R4 conversions fail saying Encounter.reasonCode is an invalid property

### ISSUE THREAD

**Issue by mcmundt** [hapifhir/org.hl7.fhir.core#196]
Edit: Added file with encounter resource that reproduces the problem
[encounter.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/4617339/encounter.txt)

When using StructureMaps to convert STU3 to R4, the conversion fails with an exception. It succeeds when using native conversion.

Command line:
java -jar org.hl7.fhir.validator.jar encounter.in.xml -version 3.0 -to-version 4.0.1 -output encounter.out.xml

org.hl7.fhir.exceptions.FHIRException: Exception executing transform tgt.reasonCode = create() as vvv on Rule "reason": Attempt to get types for an invalid property 'reasonCode' on type Encounter
	at org.hl7.fhir.r5.utils.StructureMapUtilities.runTransform(StructureMapUtilities.java:1954)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.processTarget(StructureMapUtilities.java:1825)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1412)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1399)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.transform(StructureMapUtilities.java:1361)
	at org.hl7.fhir.validation.ValidationEngine.transformVersion(ValidationEngine.java:1754)
	at org.hl7.fhir.validation.cli.services.ValidationService.transformVersion(ValidationService.java:157)
	at org.hl7.fhir.validation.Validator.main(Validator.java:168)
Caused by: org.hl7.fhir.exceptions.FHIRException: Attempt to get types for an invalid property 'reasonCode' on type Encounter
	at org.hl7.fhir.r5.model.Base.getTypesForProperty(Base.java:330)
	at org.hl7.fhir.r5.elementmodel.Element.getTypesForProperty(Element.java:707)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.runTransform(StructureMapUtilities.java:1850)
	... 7 more

**Comment by imkacarlson** [comment]
This is not limited to just an `Encounter`

I did the same thing as above but used this [Observation-example.xml](http://hl7.org/fhir/STU3/observation-example.xml.html) as the input xml and I got a similar error:

`org.hl7.fhir.exceptions.FHIRException: Exception executing transform tgt.encounter = create() as vvv on Rule "context": Attempt to get types for an invalid property 'encounter' on type Observation
	at org.hl7.fhir.r5.utils.StructureMapUtilities.runTransform(StructureMapUtilities.java:1969)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.processTarget(StructureMapUtilities.java:1840)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1427)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1414)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.transform(StructureMapUtilities.java:1376)
	at org.hl7.fhir.validation.ValidationEngine.transformVersion(ValidationEngine.java:1822)
	at org.hl7.fhir.validation.cli.services.ValidationService.transformVersion(ValidationService.java:169)
	at org.hl7.fhir.validation.Validator.main(Validator.java:179)
Caused by: org.hl7.fhir.exceptions.FHIRException: Attempt to get types for an invalid property 'encounter' on type Observation
	at org.hl7.fhir.r5.model.Base.getTypesForProperty(Base.java:312)
	at org.hl7.fhir.r5.elementmodel.Element.getTypesForProperty(Element.java:717)
	at org.hl7.fhir.r5.utils.StructureMapUtilities.runTransform(StructureMapUtilities.java:1865)
	... 7 more`

If you look at the [Observation R3 to R4 conversions](http://hl7.org/fhir/observation-version-maps.html) you see that `src.context -> tgt.encounter` showing that the names change between the versions. The same is true when we look at the [Encounter R3 to R4 conversions ](https://www.hl7.org/fhir/encounter-version-maps.html) and see that `src.reason -> tgt.reasonCode`. There seems to be an issue converting any element within a resource that has a name change from R3 to R4
