### ISSUE TITLE
Optional fhir package canonical crashes validator

### ISSUE THREAD

**Issue by vadi2** [hapifhir/org.hl7.fhir.core#34]
The [spec](http://wiki.hl7.org/index.php?title=FHIR_NPM_Package_Spec) mentions that canonicals are optionals for non-IGs, but the validator bombs out without one:

```
$ cat package.json 
{
  "name": "swedishnationalmedicationlist",
  "version": "0.1.0",
  "description": "Put a description here",
  "dependencies": {},
  "devDependencies": null,
  "canonicals": null
}
```
```
Exception in thread "main" java.lang.NullPointerException
	at org.hl7.fhir.utilities.cache.NpmPackage.canonical(NpmPackage.java:274)
	at org.hl7.fhir.utilities.cache.PackageCacheManager.extractLocally(PackageCacheManager.java:522)
	at org.hl7.fhir.r5.validation.ValidationEngine.loadPackage(ValidationEngine.java:510)
	at org.hl7.fhir.r5.validation.ValidationEngine.loadIgSource(ValidationEngine.java:432)
	at org.hl7.fhir.r5.validation.ValidationEngine.loadIg(ValidationEngine.java:661)
	at org.hl7.fhir.r5.validation.Validator.main(Validator.java:373)
```

**Comment by grahamegrieve** [comment]
fixed
