### ISSUE TITLE
Valdator 5.2.1 Inconsistent Proxy Authorization

### ISSUE THREAD

**Issue by CHFJr** [hapifhir/org.hl7.fhir.core#395]
When the validator accesses **http://packages.fhir.org/hl7.terminology** through our proxy server, it sends a **Poxy-authorization NTLM** header on the request. However when accessing **http://tx.fhir.org/r4/metadata?_summary=true** the validator only supports Basic authorization, despite the proxy server indicating support for both NTLM and Basic.

While I can just use the new -auth option to force Basic, exposing our network credentials on a command is a violation of our security practices. 

Is there something that can be done to make the validator behave consistently?

Thanks ... Charlie

Also, the validator no longer responds to /? option. It reports that the Help.txt file isn't in the .jar file.

**Comment by markiantorno** [comment]
What version of the validator are you running?

**Comment by CHFJr** [comment]
5.2.1

**Comment by CHFJr** [comment]
I just tried this with v5.2.9 and encountered the same proxy problem. I see the help file is back.

**Comment by markiantorno** [comment]
Hey Charlie, what is the exact behaviour you want from the validator?

The validator and the tx server are different codebases and different things. I can make changes to the validator.

What kind of auth do you want me to add to the CLI? Describe the exact behaviour (what the command would look like, how you want it handled internally) and I'll add it.

**Comment by markiantorno** [comment]
@CHFJr

**Comment by CHFJr** [comment]
I would like the validator to support the Proxy-authorization NTLM header for http://tx/fhir.org/r4/metadata. (See the original comment for more details.) 

Here is a copy of the command line & stack trace from 5.3.9 (The latest version I have available.)
java -Xmx3072m -Dhttp.proxyHost=proxy -Dhttp.proxyPort=9119 -jar "C:\Program Files\HL7 Validator\validator_cli.jar" -version 4.0 Sample.json

  Load hl7.terminology#2.0.0 - 3749 resources (00:03.0718)
  Terminology server http://tx.fhir.orgException in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to connect to terminology server. Use parameter '-tx n/a' to run without using terminology services to validate LOINC, SNOMED, ICD-X etc. Error = Error fetching the server's capability statement: Parameter specified as non-null is null: method okhttp3.Credentials.basic, parameter username
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:302)
        at org.hl7.fhir.validation.ValidationEngine.connectToTSServer(ValidationEngine.java:263)
        at org.hl7.fhir.validation.ValidationEngine.setTerminologyServer(ValidationEngine.java:642)
        at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:224)
        at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:208)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:202)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:158)
Caused by: org.hl7.fhir.exceptions.FHIRException: Error fetching the server's capability statement: Parameter specified as non-null is null: method okhttp3.Credentials.basic, parameter username
        at org.hl7.fhir.r5.utils.client.FHIRToolingClient.getCapabilitiesStatementQuick(FHIRToolingClient.java:158)
        at org.hl7.fhir.convertors.txClient.TerminologyClientR5.getCapabilitiesStatementQuick(TerminologyClientR5.java:99)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.connectToTSServer(SimpleWorkerContext.java:298)
        ... 6 more
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.Credentials.basic, parameter username
        at okhttp3.Credentials.basic(Credentials.kt)
        at okhttp3.Credentials.basic$default(Credentials.kt:28)
        at okhttp3.Credentials.basic(Credentials.kt)
        at org.hl7.fhir.r5.utils.client.network.FhirRequestBuilder.lambda$getHttpClient$2(FhirRequestBuilder.java:155)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.kt:220)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:108)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.hl7.fhir.r5.utils.client.network.RetryInterceptor.intercept(RetryInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.hl7.fhir.r5.utils.client.network.FhirRequestBuilder.execute(FhirRequestBuilder.java:207)
        at org.hl7.fhir.r5.utils.client.network.Client.executeFhirRequest(Client.java:213)
        at org.hl7.fhir.r5.utils.client.network.Client.issueGetResourceRequest(Client.java:92)
        at org.hl7.fhir.r5.utils.client.FHIRToolingClient.getCapabilitiesStatementQuick(FHIRToolingClient.java:155)
        ... 8 more
