### ISSUE TITLE
Package handling is case dependent

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/org.hl7.fhir.core#475]
Simplifier allowed users to create packages with capital Chars in the id. The package loader is case dependent and running into issues like this: 
````
julian@Julians-MacBook-Air kerndatensatzmodul-diagnose % java -jar validator_cli.jar Condition-example.json -version 4.0 -ig de.medizininformatikinitiative.kerndatensatz.diagnose#1.0.2
FHIR Validation tool Version 5.3.2 (Git# 7e70adf8198d). Built 2021-02-18T23:33:17.184Z (13 days old)
  Java:   15.0.2 from /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home on x86_64 (64bit). 2048MB available
  Paths:  Current = /Users/julian/git/kerndatensatzmodul-diagnose, Package Cache = /Users/julian/.fhir/packages
  Params: Condition-example.json -version 4.0 -ig de.medizininformatikinitiative.kerndatensatz.diagnose#1.0.2
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1Creating Package manager?
 - 4575 resources (00:17.0543)
  Load hl7.terminology#2.0.0 - 3749 resources (00:01.0836)
  Terminology server http://tx.fhir.org - Version 1.9.369 (00:02.0909)
  Load de.medizininformatikinitiative.kerndatensatz.meta#1.0.2 - 2 resources (00:00.0101)
  Load de.basisprofil.r4#0.9.12 - 126 resources (00:01.0198)
  Load KBV.Basis#1.1.0Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to find/resolve/read -ig KBV.Basis#1.1.0
    at org.hl7.fhir.validation.IgLoader.loadIgSource(IgLoader.java:191)
    at org.hl7.fhir.validation.IgLoader.loadIg(IgLoader.java:85)
    at org.hl7.fhir.validation.IgLoader.loadIg(IgLoader.java:71)
    at org.hl7.fhir.validation.cli.services.ValidationService.getValidator(ValidationService.java:205)
    at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:200)
    at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:156)
````

Proposed resolution: always convert the id String to lower-case before comparing.

**Comment by wardweistra** [comment]
Discussion on Zulip here: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Error.20loading.20package.20in.20java.20validator

Watching this issue, because only when this is fixed can we update packages with mixed case in Simplifier to lowercase, without impacting dependencies of current IGs.
