### ISSUE TITLE
FHIRPathEngine assumes that all extension elements declare a type

### ISSUE THREAD

**Issue by jduteau** [hapifhir/org.hl7.fhir.core#557]
Line 5500 in FHIRPathEngine.java:
StructureDefinition exsd = worker.fetchResource(StructureDefinition.class, t.getType().get(0).getProfile().get(0).getValue());

I have a differential that doesn't declare the type in one of the extension element:
```
      {
        "id": "Claim.careTeam",
        "path": "Claim.careTeam",
        "slicing": {
          "discriminator": [
            {
              "type": "value",
              "path": "extension('http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-careTeamClaimScope').value"
            }
          ],
          "rules": "open",
          "description": "Slice based on whether the care team member belongs to the overall claim or to an individual claim item."
        },
        "mustSupport": true
      },
      {
        "id": "Claim.careTeam.extension",
        "path": "Claim.careTeam.extension",
        "slicing": {
          "discriminator": [
            {
              "type": "value",
              "path": "url"
            }
          ],
          "ordered": false,
          "rules": "open"
        },
        "min": 1
      },
      {
        "id": "Claim.careTeam.extension:careTeamClaimScope",
        "path": "Claim.careTeam.extension",
        "sliceName": "careTeamClaimScope",
        "min": 1,
        "max": "1",
        "type": [
          {
            "code": "Extension",
            "profile": [
              "http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-careTeamClaimScope"
            ]
          }
        ],
        "mustSupport": true
      },
...
      {
        "id": "Claim.careTeam:OverallClaimMember",
        "path": "Claim.careTeam",
        "sliceName": "OverallClaimMember",
        "min": 0,
        "max": "14"
      },
      {
        "id": "Claim.careTeam:OverallClaimMember.extension:careTeamClaimScope",
        "path": "Claim.careTeam.extension",
        "sliceName": "careTeamClaimScope"
      },
...
      {
        "id": "Claim.careTeam:ItemClaimMember",
        "path": "Claim.careTeam",
        "sliceName": "ItemClaimMember",
        "min": 0,
        "max": "10"
      },
      {
        "id": "Claim.careTeam:ItemClaimMember.extension:careTeamClaimScope",
        "path": "Claim.careTeam.extension",
        "sliceName": "careTeamClaimScope"
      },
```

When I run the publisher, that gets the following Java uncaught exception:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.hl7.fhir.r5.utils.FHIRPathEngine.evaluateDefinition(FHIRPathEngine.java:5500)
	at org.hl7.fhir.validation.instance.InstanceValidator.getCriteriaForDiscriminator(InstanceValidator.java:3058)
	at org.hl7.fhir.validation.instance.InstanceValidator.sliceMatches(InstanceValidator.java:3554)
	at org.hl7.fhir.validation.instance.InstanceValidator.matchSlice(InstanceValidator.java:4926)
```

**Comment by markiantorno** [comment]
I put in a PR to resolve the crash. @grahamegrieve will have to review before it is merged.

https://github.com/hapifhir/org.hl7.fhir.core/pull/571
