### ISSUE TITLE
Error sorting differential during generate snapshot

### ISSUE THREAD

**Issue by nkarip** [hapifhir/org.hl7.fhir.core#562]
During the generate snapshot process we're getting an exception copied below. 

> org.hl7.fhir.exceptions.DefinitionException: Profile SHCCovid19LaboratoryResultObservationDM (http://hl7.org/fhir/uv/shc-vaccination/StructureDefinition/shc-covid19-laboratory-result-observation-dm), element null. Error generating snapshot: Error sorting Differential: The element Observation.valueString is out of order (and maybe others after it)
	at org.hl7.fhir.r5.context.SimpleWorkerContext.generateSnapshot(SimpleWorkerContext.java:785)
	at org.hl7.fhir.r5.context.SimpleWorkerContext.generateSnapshot(SimpleWorkerContext.java:752)

In debugging, it seems to be coming from org.hl7.fhir.r5.conformance.ProfileUtilities.sortDifferential(). It appears to be sorting one of the lists that it passes to compareDiff alphabetically by element name, but not the other (it looks like diffList if sorted but then not used). I can make the exception disappear by manually pre-sorting the diff elements in the StructureDefinition alphabetically.

**Comment by markiantorno** [comment]
So, I'm looking into this now, and it would be super helpful if I could reproduce this locally to debug.

Can you provide the steps and data I need to replicate this locally on my machine?

@nkarip

**Comment by alexey-tschudnowsky** [comment]
Hello @markiantorno,

not quite sure if this is the same issue, but we also ran into the same error with the current validator (5.6.99). As far as we can see, the exceptions comes from ProfileUtilities.sortDifferential-Method. It's intereseting, that HAPI Validator doesn't call sortDifferential in the [SnapshotGeneratingValidationSupport](https://github.com/hapifhir/hapi-fhir/blob/794e4510c6bf566dc2a6bb49818f198defb4355c/hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/SnapshotGeneratingValidationSupport.java#L90) class, so no such error occurs there.

One can easily reproduce it with the following [example input file](https://github.com/hapifhir/org.hl7.fhir.core/files/10841474/KBV_PR_ERP_Medication_PZN-test.xml.txt) and the call to validator below 

Maybe the issue can be reopened? I can create a new one as well. 

```
java -jar .\validator_cli.jar .\KBV_PR_ERP_Medication_PZN-test.xml -verbose -ig kbv.ita.erp#1.1.0 -version 4.0 -profile https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN
FHIR Validation tool Version 5.6.99 (Git# e2185d7d5c91). Built 2023-02-23T18:15:26.607Z (3 days old)
  Java:   11.0.14.1 from C:\Program Files\OpenJDK\openjdk-11.0.14.1_1 on amd64 (64bit). 8136MB available

WARNING: Default file encoding is windows-1252 which may cause unexpected results.
         To fix this issue, run this program with the parameter '-Dfile.encoding=UTF-8'
         Future releases may not be able to run at all with encoding windows-1252

  Paths:  Current = C:\Dev\fhir validator\5.6.99, Package Cache = C:\Users\alexey.tschudnowsky\.fhir\packages
  Params: .\KBV_PR_ERP_Medication_PZN-test.xml -verbose -ig kbv.ita.erp#1.1.0 -version 4.0 -profile https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN
  Jurisdiction: United States of America
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1.: - 4576 resources (00:04.194)
  Load hl7.terminology#4.0.0 - 4164 resources (00:01.770)
  Load R5 Extensions - 144 resources (00:02.717)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:02.982)
  Load de.basisprofil.r4#1.3.2 - 177 resources (00:00.180)
  Load KBV.Basis#1.3.0 - 146 resources (00:01.767)
  Load kbv.ita.for#1.1.0 - 20 resources (00:00.121)
  Load kbv.ita.erp#1.1.0 - 26 resources (00:00.060)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.0.12, hl7.terminology#4.0.0, de.basisprofil.r4#1.3.2, KBV.Basis#1.3.0, kbv.ita.for#1.1.0, kbv.ita.erp#1.1.0]
  Get set... Unable to generate snapshot for https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_Compounding|1.1.0: Profile KBV_PR_ERP_Medication_Compounding (https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_Compounding), element null. Error generating snapshot: Error sorting Differential: StructureDefinition https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_Compounding: Differential contains path Medication.extension.value[x].text which is actually Element.text, which is not found in the in base Element
Unable to generate snapshot for https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN|1.1.0: Profile KBV_PR_ERP_Medication_PZN (https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN), element null. Error generating snapshot: Error sorting Differential: StructureDefinition https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN: Differential contains path Medication.extension.value[x].text which is actually Element.text, which is not found in the in base Element
Unable to generate snapshot for https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_Ingredient|1.1.0: Profile KBV_PR_ERP_Medication_Ingredient (https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_Ingredient), element null. Error generating snapshot: Error sorting Differential: StructureDefinition https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_Ingredient: Differential contains path Medication.ingredient.item[x].coding which is actually Element.coding, which is not found in the in base Element
 go (00:01.751)
Validating
  Profiles: [https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN]
  Validate .\KBV_PR_ERP_Medication_PZN-test.xml
Validate Medication against https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN|1.1.0..........20..........40..........60..........80.........|
Validate Medication against https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN|
 00:01.571
Done. Times: Loading: 00:15.839, validation: 00:01.571. Memory = 537Mb

Success: 0 errors, 2 warnings, 4 notes
  Information @ Medication (line 1, col41): Validate resource against profile https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN|1.1.0
  Information @ Medication (line 1, col41): Validate resource against profile https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_PZN|1.1.0 (per meta)
  Information @ Medication.code.coding[0] (line 29, col17): Code System URI 'http://fhir.de/CodeSystem/ifa/pzn' is unknown so the code cannot be validated
  Information @ Medication.form.coding[0] (line 36, col17): Code System URI 'https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_DARREICHUNGSFORM' is unknown so the code cannot be validated
  Warning @ Medication.extension[3].value.ofType(code) (line 26, col32): ValueSet https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_KBV_NORMGROESSE not found by validator
  Warning @ Medication.form.coding[0] (line 36, col17): ValueSet https://fhir.kbv.de/ValueSet/KBV_VS_SFHIR_KBV_DARREICHUNGSFORM not found by validator
```
