### ISSUE TITLE
Java validator doesn't find R4 package

### ISSUE THREAD

**Issue by vadi2** [hapifhir/org.hl7.fhir.core#58]
Doesn't seem to work with R4, works ok with STU3:

```
FHIR Validation tool Version 3.8.11-SNAPSHOT - Built 2019-07-05T21:44:08.770Z - Git da4fc1f8602e
Arguments: -version 4.0 -ig . sample.json
  .. connect to tx server @ http://tx.fhir.org
  .. definitions from hl7.fhir.core#4.0
Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to resolve version 4.0 for package hl7.fhir.core
	at org.hl7.fhir.utilities.cache.PackageCacheManager.loadPackage(PackageCacheManager.java:634)
	at org.hl7.fhir.r5.validation.ValidationEngine.resolvePackage(ValidationEngine.java:587)
```

**Comment by grahamegrieve** [comment]
fixed
