### ISSUE TITLE
FhirPathEngine throws UnsupportedOperationException when evaluating Observation.component.valueQuantity

### ISSUE THREAD

**Issue by maimoonak** [hapifhir/org.hl7.fhir.core#592]
[FhirPathEngine](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/FHIRPathEngine.java) throws UnsupportedOperationException when evaluating Observation.component.valueQuantity

**Failing Test**

```
  @Test
  fun index_observation_quantity_type_basic() {
    val context = FhirContext.forR4()
    val fhirPathEngine =
      FHIRPathEngine(HapiWorkerContext(context, DefaultProfileValidationSupport(context)))

    val observation =
      Observation().apply {
        this.addComponent().apply {
          this.valueQuantity.apply {
            value = BigDecimal.valueOf(70)
            system = "http://unitsofmeasure.org"
          }
        }
        this.addComponent().apply {
          this.valueQuantity.apply {
            value = BigDecimal.valueOf(110)
            system = "http://unitsofmeasure.org"
          }
        }
      }

    val bases = fhirPathEngine.evaluate(observation, "(Observation.component.value as Quantity) | (Observation.component.value as SampledData)")
    org.junit.Assert.assertEquals(2, bases.size)
  }
```

**Observation example** on HAPI Server that fails http://hapi.fhir.org/baseR4/Observation/49413

**Exception trace**

```
java.lang.UnsupportedOperationException
	at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.getUcumService(HapiWorkerContext.java:289)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.qtyEqual(FHIRPathEngine.java:1670)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.doEquals(FHIRPathEngine.java:1640)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.doContains(FHIRPathEngine.java:2124)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.opUnion(FHIRPathEngine.java:2112)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.operate(FHIRPathEngine.java:1422)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1189)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:525)
	at com.google.android.fhir.index.ResourceIndexerTest.index_observation_quantity_type_basic(ResourceIndexerTest.kt:631)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
```

**Comment by markiantorno** [comment]
So I just ran this in the core library with the following test:

```java
  @Test
  public void googleTest() throws IOException, org.hl7.fhir.exceptions.FHIRException, UcumException {
    InputStream obs_input = this.getClass().getResourceAsStream("/test-obs.json");
    Observation obs = (Observation) new org.hl7.fhir.r4.formats.JsonParser().parse(obs_input);

    List<Base> bases = fp.evaluate(obs, "(Observation.component.value as Quantity) | (Observation.component.value as SampledData)");
    bases.forEach(System.out::println);
    Assertions.assertEquals(2, bases.size());
  }
```

Where `test-obs.json` is just an observation file identical to the one you linked at http://hapi.fhir.org/baseR4/Observation/49413.

The test appears to pass, and runs as expected. Could you please provide more details and reopen if this is an issue.
