### ISSUE TITLE
Missing searchParameter causes NPE

### ISSUE THREAD

**Issue by jduteau** [hapifhir/org.hl7.fhir.core#608]
I had changed a StructureDefinition and the FHIR build failed with a NullPointerException because I did not remove a search parameter for an element that no longer existed.  It resulted in the following stack trace:
Error: null
java.lang.NullPointerException
        at java.base/java.util.ResourceBundle.containsKey(ResourceBundle.java:2302)
        at org.hl7.fhir.utilities.i18n.I18nBase.messageExistsForLocale(I18nBase.java:50)
        at org.hl7.fhir.utilities.i18n.I18nBase.formatMessage(I18nBase.java:67)
        at org.hl7.fhir.validation.BaseValidator.ruleHtml(BaseValidator.java:421)
        at org.hl7.fhir.definitions.validation.ResourceValidator.rule(ResourceValidator.java:124)
        at org.hl7.fhir.definitions.validation.ResourceValidator.checkSearchParams(ResourceValidator.java:383)
        at org.hl7.fhir.definitions.validation.ResourceValidator.check(ResourceValidator.java:217)
        at org.hl7.fhir.definitions.validation.ResourceValidator.check(ResourceValidator.java:594)
        at org.hl7.fhir.tools.publisher.Publisher.validate(Publisher.java:1787)
        at org.hl7.fhir.tools.publisher.Publisher.execute(Publisher.java:609)
        at org.hl7.fhir.tools.publisher.Publisher.main(Publisher.java:474)

@markiantorno discovered that it tried to get the element for the given path which returned null which caused a problem when it tried to iterate on the element.getTypes().

**Comment by grahamegrieve** [comment]
@markiantorno this is an issue in kindling, yes?
