### ISSUE TITLE
Regression: validator CLI 5.6.43+ rejects parameter '-strictExtensions'

### ISSUE THREAD

**Issue by DarthGizka** [hapifhir/org.hl7.fhir.core#814]
From version 5.6.43 on the validator CLI fails to recognise the parameter '-strictExtensions', even though it is still listed in the help screen:

```
-strictExtensions: If present, treat extensions not defined within the specified
    FHIR version and any referenced implementation guides or profiles as errors.
    (Default is to only raise information messages.)
```

The parameter gets treated as a filename:
```
********************
* The file name you passed in, '-strictExtensions', doesn't exist on the local filesystem.
* Please verify that this is valid file location.
********************

Exception in thread "main" java.io.IOException: File -strictExtensions does not exist
        at org.hl7.fhir.validation.ValidatorUtils.extractReferences(ValidatorUtils.java:131)
        at org.hl7.fhir.validation.ValidatorUtils.parseSources(ValidatorUtils.java:155)
        at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:425)
        at org.hl7.fhir.validation.cli.services.ValidationService.validateSources(ValidationService.java:108)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:279)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:164)
```

**Comment by DarthGizka** [comment]
From version 5.6.43 on the validator CLI fails to recognise the parameter '-strictExtensions', even though it is still listed in the help screen:

```
-strictExtensions: If present, treat extensions not defined within the specified
    FHIR version and any referenced implementation guides or profiles as errors.
    (Default is to only raise information messages.)
```

**Comment by DarthGizka** [comment]
@dotasek: the [documentation for the newish `-extension` parameter][8.5] seems to imply that the `-strictExtensions` behaviour is now the default and the parameter no longer necessary. So the fix might require little more than editing [resources/help.txt](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.validation/src/main/resources/help.txt).

[8.5]: https://confluence.hl7.org/pages/viewpage.action?pageId=35718580#UsingtheFHIRValidator-Extensions
