### ISSUE TITLE
Validator crashes with MedicationRequest example

### ISSUE THREAD

**Issue by gmyers18** [hapifhir/org.hl7.fhir.core#86]
The latest validator crashes when presented with a standard STU3 MedicationRequest example.  The crash goes away if the `requester.agent.reference` field is removed.  Could someone shed some light on this for me, as I initially ran into this when trying to validate some real MedicationRequest data.

```
> java -jar org.hl7.fhir.validator.jar http://hl7.org/fhir/STU3/medicationrequest0301.json -version 3.0

FHIR Validation tool Version 4.0.22-SNAPSHOT - Built 2019-09-27T14:16:20.593+10:00 - Git fb152a24e56d
Detected Java version: 1.8.0_191 from C:\Program Files\Java\jre1.8.0_191 on amd64 (64bit). 7259MB available
Arguments: http://hl7.org/fhir/STU3/medicationrequest0301.json -version 3.0
Directories: Current = C:\temp\FHIR, Package Cache = C:\Users\XXXX\.fhir\packages
  .. connect to tx server @ http://tx.fhir.org
  .. definitions from hl7.fhir.core#3.0.1
    (v3.0.1)
  .. validate [http://hl7.org/fhir/STU3/medicationrequest0301.json]
   ..Detect format for http://hl7.org/fhir/STU3/medicationrequest0301.json
Terminology server: Check for supported code systems for http://snomed.info/sct
Exception in thread "main" java.lang.Error: Not done yet - resolve Practitioner/f007 locally (2)
        at org.hl7.fhir.r5.validation.InstanceValidator$ValidatorHostServices.resolveReference(InstanceValidator.java:269)
        at org.hl7.fhir.r5.utils.FHIRPathEngine.funcResolve(FHIRPathEngine.java:3310)
        at org.hl7.fhir.r5.utils.FHIRPathEngine.evaluateFunction(FHIRPathEngine.java:2740)
        at org.hl7.fhir.r5.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1147)
        at org.hl7.fhir.r5.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1161)
        at org.hl7.fhir.r5.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1156)
        at org.hl7.fhir.r5.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:546)
        at org.hl7.fhir.r5.utils.FHIRPathEngine.evaluateToBoolean(FHIRPathEngine.java:614)
        at org.hl7.fhir.r5.validation.InstanceValidator.checkInvariant(InstanceValidator.java:4456)
        at org.hl7.fhir.r5.validation.InstanceValidator.checkInvariants(InstanceValidator.java:4431)
        at org.hl7.fhir.r5.validation.InstanceValidator.checkInvariants(InstanceValidator.java:4320)
        at org.hl7.fhir.r5.validation.InstanceValidator.validateElement(InstanceValidator.java:3948)
        at org.hl7.fhir.r5.validation.InstanceValidator.checkChild(InstanceValidator.java:4099)
        at org.hl7.fhir.r5.validation.InstanceValidator.validateElement(InstanceValidator.java:3971)
        at org.hl7.fhir.r5.validation.InstanceValidator.start(InstanceValidator.java:2963)
        at org.hl7.fhir.r5.validation.InstanceValidator.validateResource(InstanceValidator.java:4563)
        at org.hl7.fhir.r5.validation.InstanceValidator.validate(InstanceValidator.java:833)
        at org.hl7.fhir.r5.validation.InstanceValidator.validate(InstanceValidator.java:666)
        at org.hl7.fhir.r5.validation.ValidationEngine.validate(ValidationEngine.java:1086)
        at org.hl7.fhir.r5.validation.ValidationEngine.validate(ValidationEngine.java:1000)
        at org.hl7.fhir.r5.validation.Validator.main(Validator.java:559)
```

**Comment by grahamegrieve** [comment]
fixed in 4.0.23
