### ISSUE TITLE
Validator CLI exception on Unknown ConceptMapRelationship code 'narrower' 

### ISSUE THREAD

**Issue by jawalonoski** [hapifhir/org.hl7.fhir.core#860]
I am attempting to validate a bundle of R4 resources with US Core 3.1.1 or 4.0.1. I've tried multiple combinations of parameters, but the results are always the same.

```
  Load R5 ExtensionsException in thread "main" java.lang.IllegalArgumentException: Unknown ConceptMapRelationship code 'narrower'
	at org.hl7.fhir.r5.model.Enumerations$ConceptMapRelationshipEnumFactory.fromCode(Enumerations.java:2301)
	at org.hl7.fhir.r5.model.Enumerations$ConceptMapRelationshipEnumFactory.fromCode(Enumerations.java:2286)
	at org.hl7.fhir.r5.formats.JsonParser.parseEnumeration(JsonParser.java:73)
	at org.hl7.fhir.r5.formats.JsonParser.parseConceptMapTargetElementComponentProperties(JsonParser.java:9079)
	at org.hl7.fhir.r5.formats.JsonParser.parseConceptMapTargetElementComponent(JsonParser.java:9064)
	at org.hl7.fhir.r5.formats.JsonParser.parseConceptMapSourceElementComponentProperties(JsonParser.java:9057)
	at org.hl7.fhir.r5.formats.JsonParser.parseConceptMapSourceElementComponent(JsonParser.java:9036)
	at org.hl7.fhir.r5.formats.JsonParser.parseConceptMapGroupComponentProperties(JsonParser.java:9027)
	at org.hl7.fhir.r5.formats.JsonParser.parseConceptMapGroupComponent(JsonParser.java:9010)
	at org.hl7.fhir.r5.formats.JsonParser.parseConceptMapProperties(JsonParser.java:9003)
	at org.hl7.fhir.r5.formats.JsonParser.parseConceptMap(JsonParser.java:8920)
	at org.hl7.fhir.r5.formats.JsonParser.parseResource(JsonParser.java:32338)
	at org.hl7.fhir.r5.formats.JsonParser.parseDomainResourceProperties(JsonParser.java:2035)
	at org.hl7.fhir.r5.formats.JsonParser.parseCanonicalResourceProperties(JsonParser.java:2025)
	at org.hl7.fhir.r5.formats.JsonParser.parseValueSetProperties(JsonParser.java:31555)
	at org.hl7.fhir.r5.formats.JsonParser.parseValueSet(JsonParser.java:31550)
	at org.hl7.fhir.r5.formats.JsonParser.parseResource(JsonParser.java:32574)
	at org.hl7.fhir.r5.formats.JsonParserBase.parse(JsonParserBase.java:133)
	at org.hl7.fhir.r5.conformance.ProfileUtilities.loadR5Extensions(ProfileUtilities.java:6858)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:344)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:325)
	at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:259)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:168)
```

Here is the bundle, but I'm fairly certain the exception has nothing to do with the bundle.
[31aa3086-c79a-ecf0-a02e-e36710b15e0b.json.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/9103172/31aa3086-c79a-ecf0-a02e-e36710b15e0b.json.zip)

**Comment by jawalonoski** [comment]
`FHIR Validation tool Version 5.6.50 (Git# 4a654122fb99). Built 2022-06-24T19:18:56.570Z (18 days old)`

**Comment by jawalonoski** [comment]
I needed to delete `~/.fhir`, and that resolved the issue.
