### ISSUE TITLE
IG Publisher NPE in ProfileUtilities

### ISSUE THREAD

**Issue by qligier** [hapifhir/org.hl7.fhir.core#954]
Using IG Publisher v1.2.7 (Git# 1c14c146605e), I got a null-pointer exception in ProfileUtilities:
```log
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "redirector" is null
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1207)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1862)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1157)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1157)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateSnapshot(ProfileUtilities.java:696)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshot(Publisher.java:5799)
```

In ProfileUtilities.processPaths, at the last recursive call, `redirector` is set to null at [line 1862](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/conformance/ProfileUtilities.java#L1862) and then accessed without null check at [line 1207](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/conformance/ProfileUtilities.java#L1207). In the previous calls, it was an empty list.

I've no idea how to properly fix that. Thanks!

**Comment by grahamegrieve** [comment]
How to reproduce this?

**Comment by qligier** [comment]
It's as short as:
```fsh
Profile: Issue954
Parent: CHEMEDCompositionMedicationTreatmentPlan
Id: issue-954
Title: "Issue954"
Description: "An extension of CHEMEDCompositionMedicationTreatmentPlan that reproduces issue 954"

* section.entry.id 0..0
/**
    These don't reproduce the issue.
    * section[annotation].entry.id 0..0
    * section[treatmentPlan].entry.id 0..0
    * section[originalRepresentation].entry.id 0..0
*/
```

The extended structure is [CHEMEDCompositionMedicationTreatmentPlan](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-composition-medicationtreatmentplan.html). I join a sample project: [issue-954.zip](https://github.com/hapifhir/org.hl7.fhir.core/files/9859998/issue-954.zip)

**Comment by grahamegrieve** [comment]
fixed next release
