### ISSUE TITLE
SimpleHTTPClient get method can cause 400 Bad Request if accept arg not passed

### ISSUE THREAD

**Issue by rettema** [hapifhir/org.hl7.fhir.core#961]
I found this while executing the IG Publisher tool (latest version 1.2.9) in my local environment. When the US Core IG package-list.json is retrieved, the following exception is thrown and recorded in the log output:

```
Stack Dump (for debugging):                                                      (00:46.777)
java.io.IOException: Invalid HTTP response 400 from https://hl7.org/fhir/us/core/package-list.json?nocache=1666376608514 (Bad Request) (content in c:\temp\fhir-http-4.log)
	at org.hl7.fhir.utilities.SimpleHTTPClient$HTTPResult.checkThrowException(SimpleHTTPClient.java:78)
	at org.hl7.fhir.igtools.publisher.realm.USRealmBusinessRules.fetchJson(USRealmBusinessRules.java:200)
	at org.hl7.fhir.igtools.publisher.realm.USRealmBusinessRules.fetchLatestUSCore(USRealmBusinessRules.java:176)
	at org.hl7.fhir.igtools.publisher.realm.USRealmBusinessRules.checkSD(USRealmBusinessRules.java:103)
	at org.hl7.fhir.igtools.publisher.Publisher.checkConformanceResources(Publisher.java:5081)
	at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:4980)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1084)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:913)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10732)
```

The **SimpleHTTPClient.java** class is in the FHIR Core Library and I have traced the issue to the overloaded **get(String url)** / **get(String url, String accept)** method. The IG Publisher code is calling the **get(String url)** method which in turn calls the **get(String url, String accept)** with a 'null' value for the accept argument. This 'null' value is not checked and the subsequent **c.setRequestProperty("Accept", accept);** is executed. This creates an HTTP Request Accept header with a 'null' value causing the above exception.

The fix is straightforward and is actually implemented in the **SimpleHTTPClient** **post** method where there is a 'null' value check on the accept argument. This same 'null' value check needs to be added to the get method:

    if (accept != null) {
      c.setRequestProperty("Accept", accept);
    }

**Comment by grahamegrieve** [comment]
fixed
