### ISSUE TITLE
Caused by: java.lang.AbstractMethodError: 

### ISSUE THREAD

**Issue by linxd** [hapifhir/org.hl7.fhir.core#998]
I have a class extends CustomThymeleafNarrativeGenerator   extends BaseThymeleafNarrativeGenerator :

public class CustomThymeleafNarrativeGenerator extends BaseThymeleafNarrativeGenerator {
    private List<String> myPropertyFile;

    public CustomThymeleafNarrativeGenerator(String... thePropertyFile) {
        setPropertyFile(thePropertyFile);
    }

    public void setPropertyFile(String... thePropertyFile) {
        Validate.notNull(thePropertyFile, "Property file can not be null", new Object[0]);
        this.myPropertyFile = Arrays.asList(thePropertyFile);
    }

    @Override // ca.uhn.fhir.narrative.BaseThymeleafNarrativeGenerator
    public List<String> getPropertyFile() {
        return this.myPropertyFile;
    }
}

public final class MyNarrativeGenerator extends CustomThymeleafNarrativeGenerator {
  public MyNarrativeGenerator(String... paramVarArgs) {
    super(paramVarArgs);
  }
  
  public final boolean populateResourceNarrative(FhirContext fhirContext, IBaseResource iBaseResource, Map<String, Object> map) {
      if (!this.myInitialized) {
          initialize();
      }
      super.populateResourceNarrative(fhirContext, iBaseResource, map);
      return false;
  }

}

got this :
Caused by: java.lang.AbstractMethodError: org.hl7.fhir.r5.hapi.ctx.HapiWorkerContext.fetchResourcesByType(Ljava/lang/Class;)Ljava/util/List;
	at org.hl7.fhir.r5.utils.FHIRPathEngine.<init>(FHIRPathEngine.java:361)
	at org.hl7.fhir.r5.conformance.ProfileUtilities.<init>(ProfileUtilities.java:403)
	at org.hl7.fhir.r5.utils.FHIRPathEngine.<init>(FHIRPathEngine.java:354)
	at org.hl7.fhir.r5.hapi.fhirpath.FhirPathR5.<init>(FhirPathR5.java:23)
	at org.hl7.fhir.r5.hapi.ctx.FhirR5.createFhirPathExecutor(FhirR5.java:57)
	at ca.uhn.fhir.context.FhirContext.newFhirPath(FhirContext.java:822)
	at ca.uhn.fhir.context.FhirContext.newFluentPath(FhirContext.java:800)
	at ca.uhn.fhir.narrative2.BaseNarrativeGenerator.findElementsInResourceRequiringNarratives(BaseNarrativeGenerator.java:86)
	at ca.uhn.fhir.narrative2.BaseNarrativeGenerator.applyTemplate(BaseNarrativeGenerator.java:55)
	at ca.uhn.fhir.narrative2.BaseNarrativeGenerator.populateResourceNarrative(BaseNarrativeGenerator.java:39)

**Comment by grahamegrieve** [comment]
Why do you think this is an issue with core?

**Comment by linxd** [comment]
THanks. I will try debug my app.

**Comment by linxd** [comment]
I found the final class org.hl7.fhir.r5.hapi.ctx.HapiWorkerContext extends I18nBase implements IWorkerContext {

haven't implmented the interface method :   
public <T extends Resource> List<T> fetchResourcesByType(Class<T> class_);

it's ok ?

**Comment by grahamegrieve** [comment]
I think it needs to

**Comment by linxd** [comment]
Thanks. 
I have mismatched the version of hapi-fhir and fhir-core

**Comment by jamesagnew** [comment]
You should not be explcitly including fhir-core in your project pom.xml (or gradle file) - hapi-fhir will pull in the appropriate version automatically as a trasitive dependency.
